spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pn_pojects?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  thymeleaf:
    cache: false
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml